id: P005440
initial_creation_type: ocr
source_metadata:
  id: bdr:W21933
  title: རྗེ་ལྷ་མོའི་བློ་བཟང་ཚུལ་ཁྲིམས་རྒྱ་མཚོའི་འདུལ་བ།
  author: ''
  volumes:
    5079f8486f434b1fa0da9a3a8c21f798:
      image_group_id: I4974
      title: ''
      volume_number: 1
      total_pages: 626
